name: 'Code Analyzer GHA'
description: 'GitHub action that executes Salesforce Code Analyzer against a PR.'
author: 'Roopa Mohan'
inputs:
  github_token:
    required: true
    description: secret to use
  runtype:
    required: false
    description: 'Type of run. Valid values are "simple", "dfa", "all". Defaults to "simple".'
    default: 'simple'
  engine:
    required: false
    description: 'Provide comma-separated values of Code Analyzer engine(s) to excecute. Defaults to Code Analyzer defaults based on runtype.'
  projectdir:
    required: false
    description: 'Path to project repository. Necessary when invoking sfge engine. Defaults to current directory.'
    default: './.'
  resultascomments:
    required: false
    description: 'Boolean to indicate if violations should be posted as comments. Defaults to false.'
    default: false

runs:
  using: "composite"
  steps:
    - uses: action_modules/validate-input
      with:
        runtype: ${{ inputs.runtype }}
        engine: ${{ inputs.engine }}
        projectdir: ${{ inputs.projectdir }}
        resultascomments: ${{ inputs.resultascomments }}



